---
title: "Conditional Perfect"
date: "2020-12-17"
page-layout: article
---
Like so many of his belated admirers in recent years, I came to Nick Drake's music after the fact. I don't even recall how it happened or when it was, exactly, but it was sometime within the past five years or so. I think it started with a video of an old BBC Arena documentary about him that I came across on a torrent site, and downloaded. I remember being surprised to discover from it that he was the younger brother of the actress Gabrielle Drake, who'd starred in the early-1970s sci-fi TV series *UFO* and whom I'd had a fatal attraction to as a 12-year-old after seeing her play Peter Pan at a Christmas pantomime in my hometown. Watching the documentary, I was enthralled by the grainy family photos and film footage of early-1970s Britain, which were so resonant of my own youth growing up there. Everything was familiar and poignant: the hairstyles, the back gardens, the bell-bottomed jeans.

After that I remember listening to a few albums on Spotify - *Five Leaves Left*, *Pink Moon* - but wasn't exactly blown away. I'd never been much of a fan of singer-songwriter types back in the day, and the songs were so low-key that it was hard to see what all the fuss was about. Drake was famously unappreciated in his day: the Arena documentary mentions how his live sets in pubs were a disaster because the songs couldn't be heard above the background noise. Nevertheless, a few songs did resonate: "Fruit Tree" on *Five Leaves Left*, and the haunting, wistful "River Man," with its strange time signature and unusual chords. And of course the most famous title song from *Pink Moon*, which would later introduce Drake's music to the millennial  generation as the soundtrack to a 30-second [Volkwagen commercial](https://www.youtube.com/watch?v=SUg_g67DdbA). *Five Leaves Left* remains my favorite album, however, and a year or two back "River Man" was added to my son's bedtime playlist. Since then we've listened to it  countless times together as he's been falling asleep and I never tire of hearing it. There's a great YouTube video that painstakingly explains [how to play it on guitar](https://www.youtube.com/watch?v=JUux4Uqqog8).  Last year while eating dinner alone in Jeonju, South Korea, I read Amanda Petrusich's excellent book about *Pink Moon* for the 33 1/3 album series on my iPhone.[^1] The book is packed with interesting information, as well as the testimonies of producers and musicians of what Drake's music means to them. It devotes an entire 30-page chapter to the 2000 Volkswagen commercial - needless to say a much-debated subject among Drake fans - that used a clip of "Pink Moon" as its soundtrack and jump-started the resurgence of interest in his music, including celebrities like Brad Pitt. I've been thinking of writing something about Nick Drake ever since.

Rather than a sudden blinding revelation, then, Nick Drake's music has gradually, almost imperceptibly crept over me in recent years, like ivy growing across a wall or lichen on a tree branch, to the point where it's become such a familiar part of everyday life that I can hardly imagine living without it. Drake himself is very fond of such organic metaphors - "Fruit Tree" being an obvious case in point - so it seems appropriate to think of his music in similar terms, as a kind of slow-growing plant that develops in symbiosis with its host.

All of which is to say that it was an organic, intuitive process that led me to the decision to write a blog - yet another among the many already  out there - about Nick Drake's music. Each post will focus on just one song, in no particular order, and discuss its particular meaning for me. Like the songs themselves, the posts are meandering reflections, intended to be neither analyses in the music-journalism sense nor fanboy tributes. They're about what the songs mean to me, personally. 

While the one-song-at-a-time model will be familiar to anyone who listens to the [Song Exploder](https://songexploder.net/about) podcast series, my approach is the opposite of the industry-driven one taken there. In Song Exploder the artist is given center stage to explain how their song was written and what it's about; it's the artist's understanding of the song's  meaning that's treated as the most authentic, authoritative one. I reject this assumption: for me the meaning of a song is primarily made by its audience, rather than its author. The music we hear in our everyday lives is what we make of it, deeply personal, and often contrary to its intended one. Song Exploder is a great source of information about the process by which a song was written and the meaning it had for its author, but it completely ignores the many, often contradictory meanings that a song has for its audience. While it would of course be great to have Nick Drake do a Song Exploder of "Fruit Tree" or "River Man," that unfortunately isn't an option, and my interest here isn't in providing anecdotes about the process by which he wrote those songs. I'm not even trying to propose an authoritative interpretation of the songs' meaning that is a matter for discussion or debate; I just want to talk about how I listen to those songs, and what they mean to me. Why should I bother reading them, then, you might ask. That's up to you, and you certainly don't have to. But I hope that if you do read them, you'll recognize in them something of your own experience, or even something new.

Nick Drake's music is reflective, even contemplative music. Other than at my son's bedtime, I like to listen to it alone, watching squirrels chasing one another around trees in the garden, staring out of a train window as landscapes slowly unfurl into one another, or driving on a deserted road late at night, looking out for the glowing eyes of crossing animals. It's that kind of watchfulness that I'm aiming for here: looking out for that occasional possum or raccoon in the headlights.

For many of his admirers, Nick and his music have come to b e the imaginary friend you never had, the cool elder brother who played guitar. That conditional-perfect "could have been" is in fact a central motif of his music, and I'll have more to say about it another time. Suffice to say for the moment that it's the reason for the name of this blog.

[^1]: Amanda Petrusich, [*Nick Drake’s ‘Pink Moon’*](https://www.bloomsbury.com/us/nick-drakes-pink-moon-9780826427908/) (New York: Bloomsbury, 2007), 33 1/3 series.

***






