project:
  type: website

website:
  title: "conditional perfect"
  site-url: https://conditional-perfect.netlify.app
  repo-url: https://github.com/mroberts1/conditional-perfect
  open-graph: true
  twitter-card:
    creator: "@dokoissho"
    card-style: summary_large_image
  navbar:
    right:
      - icon: mastodon
        aria-label: mastodon
        href: https://merveilles.town/@dokoissho
      - icon: github
        href: https://github.com/mroberts1
      - icon: twitter
        href: https://twitter.com/dokoissho
      - about.qmd
format:
  html:
    theme: ember.scss
    css: custom.scss
    fontsize: 1.1em
    linestretch: 1.5
    smooth-scroll: true

editor: visual

comments:
  giscus:
    repo: mroberts1/conditional-perfect


