project:
  type:
    website
  
format:
  html: 
    backgroundcolor: "#EFEDE5"
    theme: 
      light: [litera, ember.scss]
    css: custom.scss
    #self-contained: true
    grid:
        sidebar-width: 400px
        body-width: 600px
        #margin-width: 300px
        #gutter-width: 1em
    fontsize: 1.1em
    linestretch: 1.5
    smooth-scroll: true
    linkcolor: "#2E5392"
    link-external-newwindow: true
  #PrettyPDF-pdf: default
lightbox: 
  match: auto
  effect: fade
  loop: false
fig-responsive: true
image-alt: " "
execute:
  freeze: auto
